### ISSUE TITLE
Composer conversion failure

### ISSUE THREAD

**Issue by r3volution11** [pantheon-systems/terminus-conversion-tools-plugin#24]
Kevin Porras asked me to submit an issue showing what happened in my case.

The situation: the site was upgraded from Drupal 8 to Drupal 9 through alternative means – it's not composer integrated or linked to a proper upstream (Pantheon still thinks it's Drupal 8). It also has a custom-developed module that does not have a repository.

Goal: Fix that

Here's what happened when I ran the composer conversion:
[conversion.log](https://github.com/pantheon-systems/terminus-conversion-tools-plugin/files/8306945/conversion.log)

I accidentally closed the terminal tab before gathering more of the output but essentially it created the conversion multidev environment, pushed things up, and then it didn't build.

**Comment by kporras07** [comment]
@r3volution11 sorry we totally missed this but I'm taking a look to this now and the issue seems to be with phpunit and rector that are in a version that is not compatible with `core-recommended`. In case this is still an issue (I know it's been a while), could you please first update phpunit and rector to ^8 and ~0.12 respectively and then re-run the same command?

Thanks!

**Comment by kporras07** [comment]
Given how much time has passed since this issue was created, I expect this is no longer an issue so I'm closing it. Please feel free to reopen if you still need any help here

**Comment by r3volution11** [comment]
@kporras07 You finally replied over a year later and then expect me to respond within 2 days during a major US holiday? I'm on vacation! I'll let you know as soon as I'm able.

**Comment by namespacebrian** [comment]
@r3volution11 Have you had a chance to take a look?  We're going to close this again at the end of the upcoming sprint if we haven't heard back (two weeks).

**Comment by namespacebrian** [comment]
@r3volution11  No worries about the gruff reply.  It was understandable.  We weren't thinking about the holiday when we closed the ticket, and we also thought no one would reply.  We had a card in our sprint to follow up on this issue, and closed the issue in order to complete the card before the end of our sprint.
